name: binancnv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - alsa-lib=1.2.14
  - appdirs=1.4.4
  - asttokens=3.0.0
  - async-timeout=5.0.1
  - attrs=25.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.4
  - aws-c-io=0.21.2
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.33.1
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.0
  - azure-identity-cpp=1.12.0
  - azure-storage-blobs-cpp=12.14.0
  - azure-storage-common-cpp=12.10.0
  - azure-storage-files-datalake-cpp=12.12.0
  - beautifulsoup4=4.13.4
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bs4=4.13.4
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - comm=0.2.3
  - contourpy=1.3.0
  - cramjam=2.11.0
  - curl-cffi=0.13.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dateparser=1.2.2
  - dbus=1.16.2
  - debugpy=1.8.16
  - decorator=5.2.1
  - double-conversion=3.3.1
  - eventkit=1.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fastparquet=2024.11.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.1
  - freetype=2.13.3
  - frozendict=2.4.6
  - frozenlist=1.7.0
  - fsspec=2025.7.0
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - graphite2=1.3.14
  - h2=4.2.0
  - harfbuzz=11.4.1
  - hpack=4.1.0
  - html5lib=1.1
  - hyperframe=6.1.0
  - ib-insync=0.9.82
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - ipykernel=6.30.1
  - ipython=8.18.1
  - jedi=0.19.2
  - joblib=1.5.1
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.4.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keyutils=1.6.3
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.8
  - libclang13=20.1.8
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=21.0.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=6.31.1
  - libre2-11=2025.07.22
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libthrift=0.22.0
  - libtiff=4.7.0
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lxml=6.0.0
  - lz4-c=1.10.0
  - matplotlib=3.9.4
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.1.7
  - mplfinance=0.12.9b7
  - multidict=6.6.3
  - multitasking=0.0.12
  - munkres=1.1.4
  - narwhals=2.1.2
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.12.0
  - numpy=2.0.2
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.4
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.1
  - parso=0.8.4
  - pcre2=10.45
  - peewee=3.18.2
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.8
  - plotly=6.3.0
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - pycparser=2.22
  - pycryptodome=3.23.0
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pyside6=6.9.1
  - pysocks=1.7.1
  - python=3.9.23
  - python-binance=1.0.29
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2025.2
  - pyzmq=27.0.1
  - qhull=2020.2
  - qt6-main=6.9.1
  - re2=2025.07.22
  - readline=8.2
  - referencing=0.36.2
  - regex=2025.7.34
  - requests=2.32.4
  - rpds-py=0.27.0
  - s2n=1.5.23
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - soupsieve=2.7
  - stack_data=0.6.3
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - tzlocal=5.3
  - ujson=5.10.0
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - wayland=1.24.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websockets=9.1
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yarl=1.20.1
  - yfinance=0.2.58
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - ibapi==10.37.2
      - protobuf==5.29.3
